Front end network-specific configuration
Manta-Network/manta-front-end pull request #118
Opened 2022-05-20 18:24 UTC by dp3000

- [X] Add new configuration files for **dolphin**, **calamari**, and **manta** networks
- [X] Modify `src/config/index.ts` to load the default network configuration at runtime
- [X] Refactor hardcoded network references out of `public/index.html` and `src/components/Sidebar/index.tsx`
- [X] Add new `Logo` component that renders appropriate logo given the network configuration
- [X] Setup network-specific `.scss` files where any network-specific styling can go
- [X] Rename and add `.png`s for each of the different network logos

2022-05-21 17:55 UTC, bhgomes commented
Thanks for the config file setup! Can we also add at least the following to the configurations?
- blockchain node URLs
- color scheme
Once we have some more details on the network-specific differences we can do more rounds of PRs.

2022-05-21 17:59 UTC, bhgomes requested changes
This is great, thanks Drew! Can you add a switch on the frontend to choose which configuration to use at runtime? Also, please fill out a PR description so we can understand the changes at a high level.

2022-05-21 17:59 UTC, bhgomes commented on src/constants/NetworkConstants.ts
> +};
Thanks for the config file setup! Can we also add at least the following to the configurations?
- blockchain node URLs
- color scheme

Once we have some more details on the network-specific differences we can do more rounds of PRs.

2022-05-21 17:59 UTC, bhgomes commented on src/constants/NetworkConstants.ts
> +  Name: 'Dolphin',
Can we use `camelCase` variable names?

2022-05-24 19:35 UTC, bhgomes commented on src/constants/NetworkConstants.ts
> +};
Dolphin, Calamari, and Manta may all be using different styling like foreground/background colors, icons, etc.

2022-05-27 17:08 UTC, bhgomes requested changes

2022-05-27 17:08 UTC, bhgomes commented on src/config/calamari.json
> +  "PAGE_TITLE": "Calamari Testnet App",
This should just be Calamari as this is a deployment not a testnet

2022-05-27 17:24 UTC, tommyjk21 approved these changes

2022-06-01 18:35 UTC, tommyjk21 approved these changes

2022-06-02 04:17 UTC, bhgomes commented on src/config/common.json
> +  "RPC": {},
If it isn't used for anything then we can get rid of it.

2022-06-02 04:19 UTC, bhgomes approved these changes

2022-06-02 04:21 UTC, merged