Integrate design
Manta-Network/manta-front-end pull request #16
Opened 2021-09-17 07:15 UTC by Kevingislason

2021-09-18 21:46 UTC, stechu commented on src/pages/AccountPage/DepositTab.js
> +  const [, setUnsub] = useState(null);
Can you elaborate what is the effect of using an empty (or null) state here?

2021-09-18 21:46 UTC, stechu commented on src/pages/AccountPage/DepositTab.js
> +  const buttonIsDisabled =
Can you add a comments on the logic of L121, it is not entirely straight-forward here.

2021-09-18 21:46 UTC, stechu commented on src/pages/AccountPage/WithdrawTab.js
> +    for (let i = 0; i < coinSelection.current.length; i += 2) {
Why the step is 2 here?

2021-09-18 21:46 UTC, stechu commented on src/pages/TransactPage/SendTab.js
> +  const selectCoins = useCallback(() => {
Can you write an english description of coin selection algorithm here as comment?

2021-09-18 21:48 UTC, stechu commented
A meta question is: is there way we can built basic unit test for the core functionalities? 
i.e. withdraw, mint, transfer, reclaim?

2021-09-19 04:53 UTC, bhgomes commented on src/pages/TransactPage/SendTab.js
> +  const selectCoins = useCallback(() => {
+1

2021-09-19 05:11 UTC, bhgomes commented on src/config/development.json
> +    "COIN_TYPE_ID": 611,
Do we have to change this to `1` for testnet, `612` for calamari?

2021-09-19 05:14 UTC, bhgomes commented on src/pages/AccountPage/DepositTab.js
> +  const buttonIsDisabled =
Seems that the `deposit` button is disabled whenever any of these is true. See L151.

2021-09-19 05:34 UTC, bhgomes commented on src/types/MantaAssetShieldedAddress.js
> +    this.assetId = new BN(bytes.slice(0, 4), 10, 'le');
It would be nice if in the future we could do this deserialization closer to the rust code. It's unfortunate to have this be so coupled to the implementation details.

2021-09-19 05:37 UTC, bhgomes commented on src/styles/text.scss
> +.manta-blue {
In the future, we should consolidate all of our `css`, and have a style guide and asset repository. At least for mainnet, I think it's good for our overall appearance.

2021-09-19 05:38 UTC, bhgomes commented on src/styles/index.scss
> +  font-family: 'Ubuntu Mono', monospace !important;
Also font. (See comment about organization-level style guide.)

2021-09-19 05:47 UTC, bhgomes commented on src/pages/PoolPage/index.js
> +                Slippage: 18%
Is this a leftover from the demo? Or does this mean something for us? Same with L35

2021-09-19 05:49 UTC, bhgomes commented on src/components/resources/Transact/SendContent/index.js
> +          Will receive: 14 DOT
Is this demo?

2021-09-19 05:51 UTC, bhgomes commented on src/components/resources/Polkadot/ChainData/index.js
> +            itemValue="1.081B"
Is this demo?

2021-09-19 05:52 UTC, bhgomes commented on src/components/resources/Govern/GovernCard/index.js
> +          Manta Network Redemption Fee Update
Is this public facing?

2021-09-19 05:56 UTC, bhgomes commented on src/MainApp.js
> +        store.set('mantaAddresses', { 0: [], 1: [] });
What are `0` and `1` here? Is this external addresses and internal addresses?

2021-09-19 05:58 UTC, bhgomes commented on src/components/resources/Extrinsic/ExtrinsicContent/index.js
> +              0xc2324c64be243494d29171fff1145b51c7bf8501ecb92c57a84060a24d0cdb11d3a0b9447d1f7aa0e3308244ebd98954335435bd963a95
What is this hash?

2021-09-19 05:59 UTC, bhgomes commented on src/components/resources/Polkadot/Validators/index.js
> +            <TableColumnHeader label="Granpa Vote" width="11%" />
nit: "Grandpa Vote"

2021-09-19 06:00 UTC, bhgomes commented on src/components/resources/Polkadot/Validators/index.js
> +          2,103,524.3704 DOT
Is this demo?

2021-09-19 06:01 UTC, bhgomes commented on src/contexts/SignerContext.js
> +    const t = setInterval(checkSignerIsConnected, 30000);
Is this the interval that we boost because proving time is potentially expensive as per our discussion on Friday? Or is that somewhere else?

2021-09-19 06:03 UTC, bhgomes commented on src/pages/AccountPage/DepositTab.js
> +  const [, setUnsub] = useState(null);
I think that's the default value, but maybe @Kevingislason can elaborate.

2021-09-19 06:06 UTC, bhgomes commented on src/pages/AccountPage/DepositTab.js
> +      const initTx = api.tx.mantaPay.initAsset(
Is this right? Does anyone have the ability to initialize an asset?

2021-09-19 06:08 UTC, bhgomes commented on src/pages/AccountPage/WithdrawTab.js
> +    // If odd number of coins selected, we will have to mint a zero value coin
Is this a security leak? Can we learn the parity of someone's coin balance?

2021-09-19 06:12 UTC, bhgomes commented on src/pages/AccountPage/WithdrawTab.js
> +  const onReclaimFailure = async (block, error) => {
Do we need `coinSelection.current = null;` in this function?

2021-09-19 06:13 UTC, bhgomes commented on src/pages/BlockPage/index.js
> +              Block #5449198
Is this demo?

2021-09-19 06:13 UTC, bhgomes commented on src/pages/TransactPage/SendTab.js
> +  const onWithdrawFailure = (block, error) => {
Same comment as previous `onWithdrawFailure`.

2021-09-19 06:14 UTC, bhgomes commented on src/pages/TransactPage/SendTab.js
> +const SendTab = () => {
Can we reduce duplication between this and reclaims? They share a lot of code.

2021-09-19 06:16 UTC, bhgomes commented on src/services/SignerClient.js
> +export const MANTA_WALLET_BASE_PATH = `m/${BIP_44_PURPOSE_INDEX}'/${config.COIN_TYPE_ID}'/${DEFAULT_ACCOUNT_ID}'`;
How much of the code in this file needs to be here? This seems duplicated with `manta-api/signer`.

2021-09-19 06:16 UTC, bhgomes requested changes
See comments above.

2021-09-20 04:32 UTC, Kevingislason commented on src/pages/AccountPage/DepositTab.js
> +  const [, setUnsub] = useState(null);
Yeah, `null` is the default value here

2021-09-20 05:16 UTC, Kevingislason commented
> A meta question is: is there way we can built basic unit test for the core functionalities?
> i.e. withdraw, mint, transfer, reclaim?

Since most of the serious crypto logic happens in Signer, manta-front-end unit tests would look like this:

A test for private transfer would be like:
1. Use Jest to simulate the selecting `DOT` from the dropdown, typing `1` into the amount form, and pressing the submit button
2. Mock an api call to polkadot.js to get ledger state
3. Check that the correct parameters are passed to a mock manta-signer api endpoint
4. Mock a return value from the manta-signer api endpoint
5. Check that the UI renders that the transaction succeeded

I don't know, do you think this is worthwhile? The web app is pretty simple now, there is not so much business logic and essentially no crypto logic, so I think most of the things that will go wrong are likely are the kinds of things integration tests would pick up.

2021-09-20 05:21 UTC, stechu commented
> > A meta question is: is there way we can built basic unit test for the core functionalities?
> > i.e. withdraw, mint, transfer, reclaim?
> 
> Since most of the serious crypto logic happens in Signer, manta-front-end unit tests would look like this:
> 
> 1. Use Jest to simulate the selecting `DOT` from the dropdown, typing `1` into the amount form, and pressing the submit button
> 2. Mock an api call to polkadot.js to get ledger state
> 3. Check that the correct parameters are passed to a mock manta-signer api endpoint
> 4. Mock a return value from the manta-signer api endpoint
> 5. Check that the UI renders that the transaction succeeded
> 
> I don't know, do you think this is worthwhile? The web app is pretty simple now, there is not so much business logic and essentially no crypto logic, so I think most of the things that will go wrong are likely are the kinds of things integration tests would pick up.

I think a full end to end test is good to have and future updates.
Do you think it is possible to add some test within the js/React for some of the logic? like coinselection?

2021-09-20 05:31 UTC, Kevingislason commented on src/pages/PoolPage/index.js
> +                Slippage: 18%
Yes, most of the repository is demo stuff, but it's hidden from the UI now

2021-09-20 05:33 UTC, Kevingislason commented on src/styles/text.scss
> +.manta-blue {
I agree, though to be clear none of the design is my doing, and I am not great with CSS. This is something that a pure frontend dev or designer can work on when we have them.

2021-09-20 05:34 UTC, Kevingislason commented on src/styles/index.scss
> +  font-family: 'Ubuntu Mono', monospace !important;
Yeah, agreed

2021-09-20 05:35 UTC, Kevingislason commented on src/components/resources/Transact/SendContent/index.js
> +          Will receive: 14 DOT
Yeah, everything in `/resources` is demo

2021-09-20 05:35 UTC, Kevingislason commented on src/components/resources/Polkadot/ChainData/index.js
> +            itemValue="1.081B"
Yes

2021-09-20 05:36 UTC, Kevingislason commented on src/components/resources/Govern/GovernCard/index.js
> +          Manta Network Redemption Fee Update
No, this is hidden

2021-09-20 05:44 UTC, Kevingislason commented on src/MainApp.js
> +        store.set('mantaAddresses', { 0: [], 1: [] });
Right

2021-09-20 05:45 UTC, Kevingislason commented on src/components/resources/Extrinsic/ExtrinsicContent/index.js
> +              0xc2324c64be243494d29171fff1145b51c7bf8501ecb92c57a84060a24d0cdb11d3a0b9447d1f7aa0e3308244ebd98954335435bd963a95
Yeah just nonsense

2021-09-20 05:46 UTC, Kevingislason commented on src/components/resources/Polkadot/Validators/index.js
> +          2,103,524.3704 DOT
Affirmative

2021-09-20 05:51 UTC, Kevingislason commented on src/contexts/SignerContext.js
> +    const t = setInterval(checkSignerIsConnected, 30000);
The time is just arbitrary. `checkSignerIsConnected` just checks that the Signer daemon is running and we can ping it. Not actually being used anywhere yet, though I will use on the next iteration.

2021-09-20 05:55 UTC, Kevingislason commented on src/pages/AccountPage/DepositTab.js
> +      const initTx = api.tx.mantaPay.initAsset(
This is local dev chain behavior

2021-09-20 05:56 UTC, Kevingislason commented on src/pages/AccountPage/WithdrawTab.js
> +    // If odd number of coins selected, we will have to mint a zero value coin
Yeah unfortunately. Maybe we should always have the client mint a zero coin?

2021-09-20 05:59 UTC, Kevingislason commented on src/pages/AccountPage/WithdrawTab.js
> +  const onReclaimFailure = async (block, error) => {
I don't think so. If the transaction fails and the user tries their luck a second time, we want the coin selection to get reused.

2021-09-20 06:16 UTC, Kevingislason commented on src/services/SignerClient.js
> +export const MANTA_WALLET_BASE_PATH = `m/${BIP_44_PURPOSE_INDEX}'/${config.COIN_TYPE_ID}'/${DEFAULT_ACCOUNT_ID}'`;
I also thought about having Signer speak the language of keypaths, and having the web app speak the simpler language `is_external_chain` flag and `index`. 

In favor of 'simpler language'
-Web app code a little less complex
-Deduplicates path construction code (`manta-api/signer` only build paths when recovering an account)
 
In favor of keypaths:
-Consistency between signer and web app
-Fewer parameters to pass to signer / signer code a little less complex
-May eventually be desirable to display keypaths in UI

2021-09-20 06:24 UTC, Kevingislason commented on src/types/MantaAssetShieldedAddress.js
> +    this.assetId = new BN(bytes.slice(0, 4), 10, 'le');
I think I can actually get rid of this..

2021-09-20 06:26 UTC, Kevingislason commented
> Do you think it is possible to add some test within the js/React for some of the logic? like coinselection?

Coin selection is one thing it definitely makes sense to test in JS

2021-09-20 06:27 UTC, bhgomes commented on src/services/SignerClient.js
> +export const MANTA_WALLET_BASE_PATH = `m/${BIP_44_PURPOSE_INDEX}'/${config.COIN_TYPE_ID}'/${DEFAULT_ACCOUNT_ID}'`;
Later on we will have to also address account numbers. Just going to leave this here for posterity.

2021-09-21 01:13 UTC, stechu approved these changes

2021-09-21 01:13 UTC, merged