add sync status
Manta-Network/manta-front-end pull request #209
Opened 2022-07-20 12:20 UTC by dansofter

## Description

closes: #205 

---

Before we can merge this PR, please make sure that all the following items have been checked off. If any of the checklist items are not applicable, please leave them but write a little note why.

- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work
- [ ] Re-reviewed files changed in the Github PR explorer

## If PR to `staging`
- [ ] Updated relevant documentation in the code
- [ ] Test code changes manually, and describe your procedure in a comment on this PR
- [ ] Mark this PR with the correct milestone

## If PR to `main`
- [ ] Update the version number in `package.json` and `src/config/common.json`
- [ ] Update the minimum required signer version number in `src/config/common.json` if applicable
- [ ] Test following the procedure in `docs/manual_test.md`
- [ ] Update `CHANGELOG.md`
- [ ] Make sure that all PR's to `manta-signer` and `sdk` on which this PR depends are merged

2022-08-25 00:09 UTC, Kevingislason requested changes

2022-08-25 00:09 UTC, Kevingislason commented on src/contexts/privateWalletContext.tsx
> +  const syncError = useRef(false);
Also, do all of these really need `useRef`?

2022-08-25 00:09 UTC, Kevingislason commented on src/contexts/privateWalletContext.tsx
> +  const syncError = useRef(false);
I think it makes more sense to use null as a default rather than 0 for these, it's less ambiguous / confusing in the initial case where you just don't know what these values are.

2022-08-25 00:09 UTC, Kevingislason commented on src/contexts/privateWalletContext.tsx
> +  const syncError = useRef(false);
Are you sure all of this state is necessary? Some state such as `syncPercentage`, `nextSyncPercentage`, `timePerPercentage`, and `percentagePerBatch` can be computed purely from other state. You can define functions to get these values and just store them in normal constants:
```js
const percentagePerBatch = getPercentagePerBatch( );
```

2022-08-25 00:09 UTC, Kevingislason commented on src/contexts/privateWalletContext.tsx
> +  const [error, setError] = useState(false);
I think `initWalletError` is more specific

2022-08-25 00:09 UTC, Kevingislason commented on tailwind.config.js
> +        white: '#fff'
I don't think these are used anywhere, and tailwind already has `text-black` (or white) and `bg-black` (or white)

2022-08-25 04:28 UTC, bhgomes commented on src/constants/LocalStorageConstants.ts
> +  CurrentSyncSenderIndex: 'current-sync-sender-index'
Why do receivers and senders get a different name for these constants?

2022-08-25 04:28 UTC, bhgomes commented on src/contexts/privateWalletContext.tsx
> +    }
Is this the standard formatting in JS? seems all over the place. Which formatter should we use @Kevingislason ?

2022-08-30 05:12 UTC, Kevingislason commented on src/contexts/privateWalletContext.tsx
> +    }
We should use the eslint config defined in `.eslintrc` in the root directory

2022-08-30 05:44 UTC, Kevingislason requested changes
This is coming along, mostly just need to refactor some of the long / complex functions.

You also have some merge conflicts to fix btw.

Also please respond to Brandon's comments.

2022-08-30 05:44 UTC, Kevingislason commented on package.json
> +    "manta-wasm-wallet-api": "1.5.1",
You should use the same version for both of these libraries

2022-08-30 05:44 UTC, Kevingislason commented on src/components/DotLoader/index.tsx
> +export default DotLoader;
I think this should go in a more general directory inside of `components` called `Loaders`

2022-08-30 05:44 UTC, Kevingislason commented on src/components/SyncPercentage/index.tsx
> +import React from 'react';
As above, I think this should go in a more general directory inside of `components` called Loaders

2022-08-30 05:44 UTC, Kevingislason commented on src/contexts/privateWalletContext.tsx
> +      try {
Please get rid of this try catch or tell me why I am wrong

2022-08-30 05:44 UTC, Kevingislason commented on src/contexts/privateWalletContext.tsx
>      const initWallet = async () => {
This function is getting insanely long, I think it's time to factor out some subfunctions; see comments below for some suggestions

2022-08-30 05:44 UTC, Kevingislason commented on src/contexts/privateWalletContext.tsx
> +        const wasmWallet = new wasm.Wallet(wasmLedger, wasmSigner);
I think this could be a subfunction called `createWasmWallet`

2022-08-30 05:44 UTC, Kevingislason commented on src/contexts/privateWalletContext.tsx
> +        );
I think this could be a subfunction (expoerted from `privateWalletSyncContext`) called `initSyncState`

2022-08-30 05:44 UTC, Kevingislason commented on src/contexts/privateWalletContext.tsx
> +        );
I think this could be a subfunction called `restart`

2022-08-30 05:44 UTC, Kevingislason commented on src/contexts/privateWalletSyncContext.tsx
> +  const [timePerPercentage, setTimePerPercentage] = useState(0);
All of these should be initialized to `null` instead of `0`, since they are unknown values

2022-08-30 05:44 UTC, Kevingislason commented on src/contexts/privateWalletSyncContext.tsx
> +  };
This function is very long and complex, you should decompose it to separate subfunctions as much as possible, and add explanatory comments

2022-09-02 04:49 UTC, Kevingislason commented on src/contexts/privateWalletSyncContext.tsx
> +  };
Start by commenting the function, then I can make suggestions.

2022-09-02 05:03 UTC, Kevingislason commented on src/contexts/privateWalletSyncContext.tsx
> +  const [timePerPercentage, setTimePerPercentage] = useState(0);
This is a convention we use throughout the front end, and a best practice for React state in general. If a value comes from an API call, null is generally used as a default. 

UI behavior is not the point. Strictly speaking, initial values of zero not correct. For example `currentSyncReceivers` does not "really" equal zero on pageload, because there is not a current sync immediately on pageload. State should always be accurate, even when inaccuracy doesn't cause UI problems. Otherwise, application code is harder to read and debug.

>we will also need unnecessary null conditional statements
This is possible to avoid if you can modularize `updateSyncProgress`. We should only have to do a single null check.

2022-10-25 20:28 UTC, AlexParshh submitted a review, later dismissed

2023-02-02 22:49 UTC, closed without merging