Staking UI
Manta-Network/manta-front-end pull request #252
Opened 2022-09-05 16:10 UTC by dansofter

## Description

-Adds front end page to support staking on Calamari
-Adds front end support for multiple networks

---

Before we can merge this PR, please make sure that all the following items have been checked off. If any of the checklist items are not applicable, please leave them but write a little note why.

- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work
- [x] Re-reviewed files changed in the Github PR explorer

## If PR to `staging`
- [ ] Updated relevant documentation in the code
- [ ] Test code changes manually, and describe your procedure in a comment on this PR
- [ ] Mark this PR with the correct milestone

## If PR to `main`
- [x] Update the version number in `package.json` and `src/config/common.json`
- [x] Update the minimum required signer version number in `src/config/common.json` if applicable
- [x] Test following the procedure in `docs/manual_test.md`
- [x] Update `CHANGELOG.md`
- [x] Make sure that all PR's to `manta-signer` and `sdk` on which this PR depends are merged

2022-09-28 16:33 UTC, Kevingislason requested changes
@Kevin & @Danny: run eslint, fix errors, add prop types

@Kevin: Merge TS compilation PR

@Kevin: Comment functions

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/index.tsx
> +    const getDelegations = async (api) => {
@Kevingislason  move into queries file?

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/index.tsx
> +    const getUserRecentRewards = async (userDelegations) => {
@Kevingislason  break apart as much as possible, comment, and describe in design doc

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/index.tsx
> +          userDelegation.setRank(101); // i.e. > 100
@Kevingislason  handle case where the user's delegation isn't active yet

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/index.tsx
> +    const setDelegatorState = () => {
@Kevingislason think about function naming here

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/index.tsx
> +// @ts-nocheck
refactor whole file

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/index.tsx
> +  };
move validations into their own context

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/index.tsx
> +  };
@Kevingislason  duplicated on send page

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/index.tsx
> +  const publishTx = async (tx) => {
@Kevingislason  this is a general utility, move to utils

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/index.tsx
> +  };
@Kevingislason  All these functions have same form, see about refactoring

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/stakeActions.ts
> +  SET_SELECTED_UNSTAKE_REQUEST: 'SET_SELECTED_UNSTAKE_REQUEST',
@Kevingislason add SET_SELECTED_USER_DELEGATION

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/StakingTable.tsx
> +        const unstakeRequest = unstakeRequests.find(
@Kevingislason  This should be handled in stake context

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/index.tsx
> +  console.log('config.DEV_CONSOLE', config.DEV_CONSOLE);
get rid of

2022-09-28 16:33 UTC, Kevingislason commented on src/pages/StakePage/index.tsx
> +    <SubstrateContextProvider socket={'wss://crispy.baikal.testnet.calamari.systems'} >
@Kevingislason This shouldn't be hard-coded

2022-09-28 16:33 UTC, Kevingislason commented on src/styles/ag-grid.scss
> +  // border-bottom: 1px solid var(--color-border-secondary);
delete

2022-09-28 16:33 UTC, Kevingislason commented on src/styles/ag-grid.scss
> +.ag-root-wrapper {
@dansofter Can you also style the tooltip the ag-grid header tooltip text to be IBM Plex Mono?

2022-09-28 16:33 UTC, Kevingislason commented on src/styles/buttons.scss
>  }
I think we can get rid of this

2022-09-28 16:33 UTC, Kevingislason commented on src/types/AssetType.ts
> +  }
@Kevingislason double check these values

2022-09-28 16:33 UTC, Kevingislason commented on src/types/Balance.ts
> +  toString(shouldFormat, decimals = 3) {
remove default argument and specify everywhere

2022-09-28 16:33 UTC, Kevingislason commented on src/types/Collator.ts
> +    this.isActive = null; // todo: set to real value
remove comment

2022-09-28 16:33 UTC, Kevingislason commented on src/types/Collator.ts
> +  ) {
get rid of this type? or move total delegation into this type?

2022-09-28 16:33 UTC, Kevingislason commented on src/types/Delegation.ts
> +  }
construct these classes all at once instead of using `set` methods

2022-09-28 16:33 UTC, Kevingislason commented on tailwind.config.js
> +        // button: 'var(--gradient-button-primary)'
delete

2022-10-01 05:13 UTC, Kevingislason commented on src/pages/StakePage/AccountSelect.tsx
> +  }, [addressCopied]);
yeah it doesn't hurt

2022-10-04 00:13 UTC, Kevingislason commented on src/components/Navbar/ChainSelector.tsx
> +  const nodeIsDisconnected = apiState === 'ERROR' || apiState === 'DISCONNECTED';
On second thought I think this is okay

2022-10-04 00:34 UTC, Kevingislason commented on src/config/calamari.json
> +    "SUBSCAN_URL": "https://calamari.subscan.io"
Need to refactor handling of network configs

2022-10-04 00:36 UTC, Kevingislason commented on src/pages/BasePage.tsx
> +export const x = 1;
too early for this

2022-10-04 02:38 UTC, Kevingislason commented on src/pages/StakePage/Modals/StakeModal.tsx
> +  };
seems non-trivial, will leave for another day

2022-10-05 04:48 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/index.tsx
> +  };
We can do this in a separate front end general cleanup PR

2022-10-05 04:48 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/index.tsx
> +  };
I think this is fine

2022-10-05 04:51 UTC, Kevingislason commented on src/pages/StakePage/StakingTable.tsx
> +        const unstakeRequest = unstakeRequests.find(
not sure what I was thinking here, this seems fine

2022-10-05 04:57 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/stakeActions.ts
> +  SET_SELECTED_UNSTAKE_REQUEST: 'SET_SELECTED_UNSTAKE_REQUEST',
already covered by `selectedCollatorDelegation`

2022-10-05 18:41 UTC, Kevingislason commented on src/pages/StakePage/StakeContext/stakeReducer.ts
> +  console.log('setUnstakeRequests reducer', setUnstakeRequests);
get rid of

2022-10-05 18:53 UTC, Kevingislason requested changes
-add back signer connection status label
-add calamari production url
-min stake too high

2022-10-05 19:08 UTC, Kevingislason submitted a review, later dismissed

2022-10-06 04:02 UTC, AlexParshh submitted a review, later dismissed
looks good!

2022-10-06 16:42 UTC, AlexParshh approved these changes

2022-10-06 19:02 UTC, merged