fix staking ui feedback
Manta-Network/manta-front-end pull request #271
Opened 2022-10-12 14:33 UTC by dansofter

## Description

-Fixes issue with urls ignoring params before '#' by getting rid of hash router
-Show only active collators by default
-Reduce staking component width to improve UX on narrower screens
-Adds balance display to stake modals
-Adds call to action for users to run collators
-Adds APY display to staking table

---

Before we can merge this PR, please make sure that all the following items have been checked off. If any of the checklist items are not applicable, please leave them but write a little note why.

- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work
- [x] Re-reviewed files changed in the Github PR explorer

## If PR to `staging`
- [x] Updated relevant documentation in the code
- [x] Test code changes manually, and describe your procedure in a comment on this PR
- [x] Mark this PR with the correct milestone

## If PR to `main`
- [ ] Update the version number in `package.json` and `src/config/common.json`
- [ ] Update the minimum required signer version number in `src/config/common.json` if applicable
- [ ] Test following the procedure in `docs/manual_test.md`
- [ ] Update `CHANGELOG.md`
- [ ] Make sure that all PR's to `manta-signer` and `sdk` on which this PR depends are merged

2022-10-13 05:17 UTC, Kevingislason requested changes

2022-10-13 05:17 UTC, Kevingislason commented on src/pages/StakePage/Tables/StakingTable.tsx
> +      ),
You also need to handle the case where the collator that the user delegated to is not in the collator candidates, i.e. the collator became inactive. In that case, you can just display 0%

2022-10-17 20:37 UTC, AlexParshh approved these changes

2022-10-23 23:35 UTC, Kevingislason reviewed
Mostly looks good. The one thing I'd change is that the balance display in the modal looks strange, being out of alignment with "Staked" and "Minimum Stake", I think it should go right under those.

Also wanted to tack on a few small things to this PR:
1. Remove the "Status" column from the collators table (but not the staking table); users can tell a collator is inactive from the filters, and from the APY.
2. 1^^ will allow us to make the collators table less wide, so we can reduce its width until the table cell holding the buttons is just about touching the side of the table. We can also reduce the width of the other two tables by the same amount.
3. Chloe suggested we restyle "Launch your own collator" to look like this:
 
![unknown-2](https://user-images.githubusercontent.com/33131270/197423732-efd85907-b582-4256-9deb-c761244f9d4f.png)

2022-10-23 23:35 UTC, Kevingislason commented on src/MainApp.tsx
> +              console.log({ props });
delete

2022-10-25 22:13 UTC, Boyuan-Deng commented
Nice work Danny, most of the changes look good.

Want to open a small design discussion here, in the dark mode, I would prefer a whiter color for "Active / All / Inactive" to make it stands out and match the color when there is text inside the search bar.
![image](https://user-images.githubusercontent.com/61630725/197891776-ae9c0440-36d6-4192-b604-47d59cef8f9e.png)
![image](https://user-images.githubusercontent.com/61630725/197891950-e57e1209-3fbe-489b-adf7-6f22b3bf61e5.png)

2022-10-25 22:19 UTC, Boyuan-Deng approved these changes
Opened a small design discussion but the rest Looks good to me

2022-10-27 06:34 UTC, Kevingislason approved these changes

2022-10-27 15:17 UTC, Boyuan-Deng commented on src/config/development.json
>      "DOLPHIN_PROVIDER_SOCKET": "wss://ws.rococo.dolphin.engineering",
I think the dolphin_provider_socket also changed but not sure we want to include in this PR @Kevingislason [c3.dolphin.engineering](https://polkadot.js.org/apps/?rpc=wss%253A%252F%252Fc3.dolphin.engineering)

2022-10-27 15:25 UTC, Boyuan-Deng commented on src/pages/StakePage/Tables/StakingTable.tsx
> +      <div style={{ maxWidth: MAX_TABLE_WIDTH }} className="mt-20 mx-auto">
would be best if we can avoid style and use className

2022-10-27 15:25 UTC, Boyuan-Deng commented on src/pages/StakePage/Tables/UnstakingTable.tsx
> +    <div style={{ maxWidth: MAX_TABLE_WIDTH }} className="mt-8 mx-auto">
would be best if we can avoid style and use className to keep css consistent

2022-10-27 15:31 UTC, Boyuan-Deng approved these changes
Nice work Danny! Please consider the comments above. Otherwise, the code LGTM

2022-10-27 17:31 UTC, Boyuan-Deng commented on src/config/development.json
>      "DOLPHIN_PROVIDER_SOCKET": "wss://ws.rococo.dolphin.engineering",
Ignore this comment. I think we should include it in another PR

2022-10-27 20:09 UTC, merged