initial commit
Manta-Network/manta-front-end pull request #318
Opened 2022-12-01 06:16 UTC by Kevingislason

## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been checked off. If any of the checklist items are not applicable, please leave them but write a little note why.

- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work
- [ ] Re-reviewed files changed in the Github PR explorer

## If PR to `staging`
- [ ] Updated relevant documentation in the code
- [ ] Test code changes manually, and describe your procedure in a comment on this PR
- [ ] Mark this PR with the correct milestone

## If PR to `main`
- [ ] Update the version number in `package.json` and `src/config/common.json`
- [ ] Update the minimum required signer version number in `src/config/common.json` if applicable
- [ ] Test following the procedure in `docs/manual_test.md`
- [ ] Update `CHANGELOG.md`
- [ ] Make sure that all PR's to `manta-signer` and `sdk` on which this PR depends are merged

2022-12-02 05:35 UTC, Boyuan-Deng commented on src/components/Error/FormErrorText.tsx
> +// @ts-nocheck
I do not think this component is used anymore. Maybe I can delete it but let me know if you think otherwise

2022-12-02 06:23 UTC, Boyuan-Deng submitted a review, later dismissed
Nothing too much. Just a few thoughts and comments. The code quality looks really good. Honestly, I learned a lot from reading code you wrote. Good work!!! Will conduct another extensive UI interaction test once you finish with all changes and then we can merge into main.

- [ ] also in connect wallet modal, install & connect seems to lost the blue background

2022-12-02 06:23 UTC, Boyuan-Deng commented on src/eth/EthXCM.ts
> +const CALAMARI_DESTINATION_WEIGHT = '4000000000'
Might be better to put into config or a constant file

2022-12-02 06:23 UTC, Boyuan-Deng commented on src/pages/BridgePage/BridgeAssetErrorText.tsx
> +// @ts-nocheck
Okay to delete IMO

2022-12-02 06:23 UTC, Boyuan-Deng commented on src/pages/BridgePage/BridgeContext/BridgeDataContext.tsx
> +  const originAddress = originChain.xcmAdapter.chain.type === 'ethereum'
I did encounter cases of originChain being undefined and cause the webpage to froze because of error so better to do null checking here originChain?.xcmAdapter...

2022-12-02 06:23 UTC, Boyuan-Deng commented on src/pages/BridgePage/BridgeContext/BridgeDataContext.tsx
> +      const originChainIsEvm = originChain.xcmAdapter.chain.type === 'ethereum';
same as above, null checking

2022-12-05 03:12 UTC, Kevingislason commented on src/components/Sidebar/SidebarMenu.tsx
> +    <div className="menu-content lg:py-4">
the file isn't used, going to delete

2022-12-05 03:17 UTC, Kevingislason commented on src/config/common.json
> +    "DOLPHIN_PROVIDER_SOCKET": "wss://c3.dolphin.seabird.systems",
Good call, asking devops team

2022-12-05 03:20 UTC, Kevingislason commented on src/eth/EthXCM.ts
> +const CALAMARI_DESTINATION_WEIGHT = '4000000000'
Think I will leave these, the constants here are and will only ever be only relevant within this file, so it improves readability to keep them here. I will move all of this functionality into our XCM library pretty soon.

2022-12-11 15:39 UTC, AlexParshh submitted a review, later dismissed

2022-12-12 04:21 UTC, Boyuan-Deng approved these changes
LGTM, thx for the hard work!

2022-12-12 04:21 UTC, Boyuan-Deng commented on src/components/Accounts/BridgeAccountSelectDropdown.tsx
>  // @ts-nocheck
Do not think this file is still being used. Should be okay to remove

2022-12-12 04:21 UTC, Boyuan-Deng commented on src/pages/SendPage/SendToForm/ToAccountSelect.tsx
> +// @ts-nocheck
ToAccountSelect Not really being used here. Maybe remove if not intend to use it in the future

2022-12-20 02:42 UTC, Boyuan-Deng approved these changes
Pretty large PR to review. Nice refactoring work. 
For most changes related to Manta SDK (inside private wallet context), I reviewed on code styles not functionality. Will test it out more using deployed website. 

Overall, I left a or two comments which are pretty small things. The code quality is solid and LGTM

2022-12-20 05:45 UTC, AlexParshh requested changes

2022-12-20 05:45 UTC, AlexParshh commented on src/types/AssetType.ts
> +  //   return CalamariAssetIds;
remove comment

2022-12-20 05:45 UTC, AlexParshh commented on src/types/AssetType.ts
> +    if (config.NETWORK_NAME === 'Dolphin') {
maybe we can use the NETWORKS object here instead of hardcoding the strings of network names ? I think there was a file called NetworkConstants.ts

2022-12-20 05:45 UTC, AlexParshh commented on src/pages/SendPage/SendContext/index.tsx
> +  // todo: get rid of
manta-js has this as a static method on MantaPrivateWallet, so can probably replace this todo with MantaPrivateWallet.assetIdToUInt8Array

2022-12-20 05:45 UTC, AlexParshh commented on src/pages/SendPage/SendContext/index.tsx
>        return null;
I think this logic of checking native token for public balance is all in the MantaUtilites.getPublicBalance method in manta-js, but again not sure if it offers enough customizability, but it would make this a bit cleaner

2022-12-20 05:45 UTC, AlexParshh commented on src/components/Navbar/Navs.tsx
> +        to="/stake"
is there a reason we want to keep this comment>

2022-12-20 05:45 UTC, AlexParshh commented on src/contexts/privateWalletContext.tsx
>        walletIsBusy.current = true;
do we still want to handle walletIsBusy on the front-end as well? I think we added it manta-js now too

2022-12-20 05:45 UTC, AlexParshh commented on src/contexts/privateWalletContext.tsx
>        console.log(
double logging since we have manta-js loggin, as per other comment

2022-12-20 17:46 UTC, Kevingislason commented on src/pages/SendPage/SendContext/index.tsx
> +  const publicTransfer = async () => {
Yeah, that needs to accept tsResHandler as a parameter before it is useful on the front end

2022-12-20 18:49 UTC, Kevingislason commented
>is there a reason we want to keep this comment
we're going to add this back soon

2022-12-20 22:25 UTC, AlexParshh approved these changes

2022-12-21 19:12 UTC, Boyuan-Deng approved these changes
Great bug catch especially for the ss58. I commented on one fix which I did not understand the bug it is trying to resolve but everything else looks good to me.

2022-12-21 19:12 UTC, Boyuan-Deng commented on src/pages/BridgePage/BridgeContext/BridgeDataContext.tsx
> +  }, [externalAccount]);
Out of curiosity, what problem is being resolved by this useeffect? "fix evm address not detected on change substrate address" was a little bit unclear for me. Would appreciate a more detailed description of the bug.

2022-12-22 06:19 UTC, Kevingislason commented on src/pages/BridgePage/BridgeContext/BridgeDataContext.tsx
> +  }, [externalAccount]);
So suppose I entered an address into the address input on the bridge page (when sending to or from Moonriver). If I changed my public account, my address would be cleared from app state, so I wouldn't be able to submit a transaction and the button would show "Enter substrate address" \ "Enter EVM address". However, I would still see my address in the form.

2022-12-22 07:57 UTC, AlexParshh submitted a review, later dismissed

2022-12-23 15:01 UTC, Kevingislason commented on src/components/Navbar/Navs.tsx
> +        to="/stake"
Yeah, we are likely going to add this back soon

2022-12-28 21:46 UTC, Apokalip approved these changes
lgmt

2022-12-28 23:58 UTC, Boyuan-Deng approved these changes

2022-12-29 00:05 UTC, merged