dont show tx history older than 6 months
Manta-Network/manta-front-end pull request #546
Opened 2023-02-21 00:46 UTC by Kevingislason

## Description

Don't show transaction history older than 6 months; this was a missed requirement for the original transaction history feature.

---

Before we can merge this PR, please make sure that all the following items have been checked off. If any of the checklist items are not applicable, please leave them but write a little note why.

- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work
- [ ] Re-reviewed files changed in the Github PR explorer

## If PR to `staging`
- [ ] Updated relevant documentation in the code
- [ ] Test code changes manually, and describe your procedure in a comment on this PR
- [ ] Mark this PR with the correct milestone

2023-02-21 01:02 UTC, jincan39 commented
LGTM

2023-02-21 01:02 UTC, jincan39 approved these changes

2023-02-21 01:12 UTC, jincan39 requested changes

2023-02-21 01:12 UTC, jincan39 commented on src/utils/persistence/privateTransactionHistory.ts
> +    return sixMonthsAgo < event.date;
sixMonthsAgo 's type not match with TxHistoryEvent.date's type
`return sixMonthsAgo < event.date.valueOf();`

2023-02-21 01:36 UTC, jincan39 requested changes

2023-02-21 01:36 UTC, jincan39 commented on src/utils/persistence/privateTransactionHistory.ts
> +  .filter((event): TxHistoryEvent => {
return type not matched
think it should be like `.filter((event: TxHistoryEvent): boolean => `

2023-02-21 01:50 UTC, zhangjing28 commented on src/utils/persistence/privateTransactionHistory.ts
> +  .filter((event): TxHistoryEvent => {
Agree with Jincan here, actually, you don't have to add the return type of the `map` and `filter` callback function. Typescript is smart enough to know it

2023-02-22 01:48 UTC, zhangjing28 approved these changes

2023-02-22 02:31 UTC, jincan39 approved these changes

2023-02-22 03:37 UTC, jasonintju approved these changes

2023-02-22 04:42 UTC, merged