Staging v5.0.4
Manta-Network/manta-front-end pull request #821
Opened 2023-03-21 22:36 UTC by Kevingislason

## Description

Release v5.0.4

---

Before we can merge this PR, please make sure that all the following items have been checked off. If any of the checklist items are not applicable, please leave them but write a little note why.

- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work
- [ ] Re-reviewed files changed in the Github PR explorer

## If PR to `main`
- [ ] Update the version number in `package.json` and `src/config/common.json`
- [ ] Update the minimum required signer version number in `src/config/common.json` if applicable
- [ ] Test following the procedure in `docs/manual_test.md`
- [ ] Update `CHANGELOG.md`
- [ ] Make sure that all PR's to `manta-signer` and `sdk` on which this PR depends are merged

2023-03-23 00:21 UTC, Kevingislason commented
Reverted #750 because it caused some strange CSS issue where the button in the attached photo would appear without its normal gradient background. We can revisit this bit later.
<img width="386" alt="Screen Shot 2023-03-22 at 8 21 13 PM" src="https://user-images.githubusercontent.com/33131270/227067580-d3d0c7c7-65a8-4e6e-ae1f-f303cd6a2d7b.png">
<img width="424" alt="Screen Shot 2023-03-22 at 8 20 16 PM" src="https://user-images.githubusercontent.com/33131270/227067583-8d797e03-4962-4417-9b3d-9aca3de60ddf.png">

2023-03-23 02:34 UTC, jincan39 submitted a review, later dismissed
LGTM

2023-03-23 03:19 UTC, jasonintju commented on CHANGELOG.md
> +- [\#753](Branch) Fix a single disconnected network on Bridge Page from preventing all transactions
Just curious, what does 'Branch' mean here? If there isn't a link here, click '#753' won't work.

2023-03-23 03:19 UTC, jasonintju submitted a review, later dismissed

2023-03-28 02:18 UTC, jincan39 approved these changes

2023-03-28 03:13 UTC, jasonintju requested changes

2023-03-28 03:13 UTC, jasonintju commented on CHANGELOG.md
> +## [5.0.3] - 2023-3-15
Repeated [5.0.3]

2023-03-28 13:49 UTC, Kevingislason commented on CHANGELOG.md
> +## [5.0.3] - 2023-3-15
nice catch, thanks

2023-03-28 13:53 UTC, jincan39 submitted a review, later dismissed

2023-03-28 13:57 UTC, jasonintju commented on CHANGELOG.md
> +- [\#753](https://github.com/Manta-Network/manta-front-end/pull/732) Fix a single disconnected network on Bridge Page from preventing all transactions
take it easy, the link should be 753

2023-03-28 14:00 UTC, jincan39 approved these changes
should we put #829 and #753 in same line if they fixed the same issue

2023-03-28 19:22 UTC, Kevingislason commented
I don't know what the proper convention is tbh

2023-03-28 19:29 UTC, merged